name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Install playwright
      run:  npx playwright install 

    - name: Run tests
      run: npm run test
      
    - name: Archive test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-results